/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AddTaskRouteImport } from './routes/addTask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as TodoIdIndexRouteImport } from './routes/$todoId/index'
import { Route as CategoriesNewCategoryRouteImport } from './routes/categories/newCategory'
import { Route as TodoIdEditRouteImport } from './routes/$todoId/edit'
import { Route as CategoriesCategoryIdIndexRouteImport } from './routes/categories/$categoryId/index'
import { Route as CategoriesCategoryIdEditRouteImport } from './routes/categories/$categoryId/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTaskRoute = AddTaskRouteImport.update({
  id: '/addTask',
  path: '/addTask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoIdIndexRoute = TodoIdIndexRouteImport.update({
  id: '/$todoId/',
  path: '/$todoId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewCategoryRoute = CategoriesNewCategoryRouteImport.update({
  id: '/categories/newCategory',
  path: '/categories/newCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoIdEditRoute = TodoIdEditRouteImport.update({
  id: '/$todoId/edit',
  path: '/$todoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdIndexRoute =
  CategoriesCategoryIdIndexRouteImport.update({
    id: '/categories/$categoryId/',
    path: '/categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesCategoryIdEditRoute =
  CategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addTask': typeof AddTaskRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/$todoId/edit': typeof TodoIdEditRoute
  '/categories/newCategory': typeof CategoriesNewCategoryRoute
  '/$todoId/': typeof TodoIdIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
  '/categories/$categoryId/': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addTask': typeof AddTaskRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/$todoId/edit': typeof TodoIdEditRoute
  '/categories/newCategory': typeof CategoriesNewCategoryRoute
  '/$todoId': typeof TodoIdIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addTask': typeof AddTaskRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/$todoId/edit': typeof TodoIdEditRoute
  '/categories/newCategory': typeof CategoriesNewCategoryRoute
  '/$todoId/': typeof TodoIdIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
  '/categories/$categoryId/': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addTask'
    | '/profile'
    | '/settings'
    | '/$todoId/edit'
    | '/categories/newCategory'
    | '/$todoId/'
    | '/categories/'
    | '/categories/$categoryId/edit'
    | '/categories/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addTask'
    | '/profile'
    | '/settings'
    | '/$todoId/edit'
    | '/categories/newCategory'
    | '/$todoId'
    | '/categories'
    | '/categories/$categoryId/edit'
    | '/categories/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/addTask'
    | '/profile'
    | '/settings'
    | '/$todoId/edit'
    | '/categories/newCategory'
    | '/$todoId/'
    | '/categories/'
    | '/categories/$categoryId/edit'
    | '/categories/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddTaskRoute: typeof AddTaskRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TodoIdEditRoute: typeof TodoIdEditRoute
  CategoriesNewCategoryRoute: typeof CategoriesNewCategoryRoute
  TodoIdIndexRoute: typeof TodoIdIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CategoriesCategoryIdEditRoute: typeof CategoriesCategoryIdEditRoute
  CategoriesCategoryIdIndexRoute: typeof CategoriesCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addTask': {
      id: '/addTask'
      path: '/addTask'
      fullPath: '/addTask'
      preLoaderRoute: typeof AddTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$todoId/': {
      id: '/$todoId/'
      path: '/$todoId'
      fullPath: '/$todoId/'
      preLoaderRoute: typeof TodoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/newCategory': {
      id: '/categories/newCategory'
      path: '/categories/newCategory'
      fullPath: '/categories/newCategory'
      preLoaderRoute: typeof CategoriesNewCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$todoId/edit': {
      id: '/$todoId/edit'
      path: '/$todoId/edit'
      fullPath: '/$todoId/edit'
      preLoaderRoute: typeof TodoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/': {
      id: '/categories/$categoryId/'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId/'
      preLoaderRoute: typeof CategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/edit': {
      id: '/categories/$categoryId/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/categories/$categoryId/edit'
      preLoaderRoute: typeof CategoriesCategoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddTaskRoute: AddTaskRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TodoIdEditRoute: TodoIdEditRoute,
  CategoriesNewCategoryRoute: CategoriesNewCategoryRoute,
  TodoIdIndexRoute: TodoIdIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CategoriesCategoryIdEditRoute: CategoriesCategoryIdEditRoute,
  CategoriesCategoryIdIndexRoute: CategoriesCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
